In [23]:
print("everything is perfect for starting the coding.")

everything is perfect for starting the coding.

In [24]:
import pandas as pd

In [25]:
data=pd.read_csv("https://raw.githubusercontent.com/Ankit152/IMDB-sentiment-analysis/master/IMDB-Dataset.csv")

In [27]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [28]:
data.tail()

                                                  review sentiment
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

In [29]:
data.shape

(50000, 2)

In [30]:
data.sample(10)

                                                  review sentiment
37207  How can a movie have Ozzy Osbourne and still s...  negative
37315  Beloved tale of hero "Benji" ("Higgins" the do...  negative
13672  Melvyn Douglas and Joan Blondell co-star in "T...  positive
33629  When I think of Return of the Jedi I think epi...  positive
33360  I've heard many things about Beowulf, maybe be...  negative
35353  OK this will contain spoilers. Now I have neve...  negative
35196  This movie is AWFUL. I haven't laughed so hard...  negative
33570  SPOILERS HEREIN<br /><br />My High School did ...  negative
8023   Richard Abernethie, a very wealthy man, has di...  positive
17118  That's what the title should be, anyway.<br />...  negative

In [31]:
data["review"][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [32]:
data["review"][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

## Data preprocessing steps
1. tokenization
2. lowercase
3. uppercase
4. emojis
5. pancuations
6. html,url
7. stopwords
8. abbrevation or slang
9. stemming and lemmetization
10. spelling correction
11. whitespace

## 1. Lowercasing & Uppercasing

In [33]:
data["review"][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [34]:
data["review"][3].upper()

"BASICALLY THERE'S A FAMILY WHERE A LITTLE BOY (JAKE) THINKS THERE'S A ZOMBIE IN HIS CLOSET & HIS PARENTS ARE FIGHTING ALL THE TIME.<BR /><BR />THIS MOVIE IS SLOWER THAN A SOAP OPERA... AND SUDDENLY, JAKE DECIDES TO BECOME RAMBO AND KILL THE ZOMBIE.<BR /><BR />OK, FIRST OF ALL WHEN YOU'RE GOING TO MAKE A FILM YOU MUST DECIDE IF ITS A THRILLER OR A DRAMA! AS A DRAMA THE MOVIE IS WATCHABLE. PARENTS ARE DIVORCING & ARGUING LIKE IN REAL LIFE. AND THEN WE HAVE JAKE WITH HIS CLOSET WHICH TOTALLY RUINS ALL THE FILM! I EXPECTED TO SEE A BOOGEYMAN SIMILAR MOVIE, AND INSTEAD I WATCHED A DRAMA WITH SOME MEANINGLESS THRILLER SPOTS.<BR /><BR />3 OUT OF 10 JUST FOR THE WELL PLAYING PARENTS & DESCENT DIALOGS. AS FOR THE SHOTS WITH JAKE: JUST IGNORE THEM."

In [41]:
data["review"] = data["review"].str.lower()

In [36]:
data["review"]

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [37]:
data["review"] = data["review"].str.upper()

In [38]:
data["review"]

0        ONE OF THE OTHER REVIEWERS HAS MENTIONED THAT ...
1        A WONDERFUL LITTLE PRODUCTION. <BR /><BR />THE...
2        I THOUGHT THIS WAS A WONDERFUL WAY TO SPEND TI...
3        BASICALLY THERE'S A FAMILY WHERE A LITTLE BOY ...
4        PETTER MATTEI'S "LOVE IN THE TIME OF MONEY" IS...
                               ...
49995    I THOUGHT THIS MOVIE DID A DOWN RIGHT GOOD JOB...
49996    BAD PLOT, BAD DIALOGUE, BAD ACTING, IDIOTIC DI...
49997    I AM A CATHOLIC TAUGHT IN PAROCHIAL ELEMENTARY...
49998    I'M GOING TO HAVE TO DISAGREE WITH THE PREVIOU...
49999    NO ONE EXPECTS THE STAR TREK MOVIES TO BE HIGH...
Name: review, Length: 50000, dtype: object

In [39]:
type(data["review"])

pandas.core.series.Series

## 2. Tackle html tags and url

In [28]:
text="""<!DOCTYPE html><html lang="en"><head><meta
charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta
name="viewport" content="width=device-width,
initial-scale=1.0"><title>Welcome to My
Website</title><style>body{font-family:'Arial',sans-serif;background-color
:#f0f0f0;color:#333;margin:20px}h1{color:#007bff}p{line-height:1.5}</style
></head><body><header><h1>Welcome to My Awesome
Website!</h1></header><main><p>This is a sample HTML document created for
demonstration purposes.</p><p>Feel free to explore and enjoy the content
on this website.</p></main><footer><p>&copy; 2024 My Website. All rights
reserved.</p></footer></body></html>"""

In [1]:
import re

The pattern <.*?> is a regular expression (regex) used to match HTML tags. Here's a breakdown:

**<: Matches the opening angle bracket of an HTML tag**

**.*?: Matches any sequence of characters (. matches any character, * means zero or more occurences), but the ? makes it non-greedy. This ensures it matches the shortest possible sequence between < and >**

**>: Matches the closing angle bracket of an HTML tag**

***Example:
For the input `<p>Hello</p>`, the pattern `<.*?>` will match:
`<p>`
`</p>`
The function `remove_html_tags` `replaces these matches` with an `empty string`, effectively removing HTML tags from the text

In [30]:
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub("",text)

In [31]:
remove_html_tags(text)

'<meta\ncharset="UTF-8"><meta\nname="viewport" content="width=device-width,\ninitial-scale=1.0">Welcome to My\nWebsitebody{font-family:\'Arial\',sans-serif;background-color\n:#f0f0f0;color:#333;margin:20px}h1{color:#007bff}p{line-height:1.5}</style\n>Welcome to My Awesome\nWebsite!This is a sample HTML document created for\ndemonstration purposes.Feel free to explore and enjoy the content\non this website.&copy; 2024 My Website. All rights\nreserved.'

In [33]:
data["review"]=data["review"].apply(remove_html_tags)
data["review"]

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

### Note: you can do(you can remove the url) it using the regex

In [2]:
text2="Check out my website at https://www.youtube.com/watch?v=V9tJCQoBakA&t=225s"
print(text2)

Check out my website at https://www.youtube.com/watch?v=V9tJCQoBakA&t=225s

The pattern r'https?://\S+|www\.\S+' is a regular expression (regex) used to match URLs. Here's the explaimation:

https?://:

Matches the literal "http://" or "https://"
The s? makes the "s" optional, so it matches both "http" and "https"

\S+:
Matches one or more non-whitespace characters (\S means any character that is not a space)
Esnures the URL continues until a space or end of the text

|:
Acts as an OR operator. Matches either the first pattern (https?://\S+) or the second

www\.\S+:
Matches URLs starting with "www.", followed by one or more non-whitespace characters.
The \. matches the literal dot . after "www".

In [3]:
def remove_url(text):
    pattern=re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub("",text)

In [4]:
remove_url(text2)

'Check out my website at '

### We gonna handle panctuations

In [10]:
import string

In [11]:
exclude = string.punctuation

In [12]:
for char in exclude:
    print(char)

!
"
#
$
%
&
'
(
)
*
+
,
-
.
/
:
;
<
=
>
?
@
[
\
]
^
_
`
{
|
}
~

In [5]:
def remove_punctuation(text):
    for char in exclude:
        text = text.replace(char, "")
    return text

In [6]:
text="string @ *() with punctuation.!"

In [13]:
remove_punctuation(text)

'string   with punctuation'

In [19]:
sent = remove_punctuation(text)
word_lst = [word for word in sent.split(" ") if len(word)>0]
cleaned_sent = " ".join(word_lst)
print(cleaned_sent)

string with punctuation

In [20]:
text2="my name is su@@@nnn$$$&&%%y"

In [21]:
remove_punctuation(text2)

'my name is sunnny'

In [42]:
data

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [44]:
data["review"]=data["review"].apply(remove_punctuation)

In [45]:
data["review"]

0        one of the other reviewers has mentioned that ...
1        a wonderful little production br br the filmin...
2        i thought this was a wonderful way to spend ti...
3        basically theres a family where a little boy j...
4        petter matteis love in the time of money is a ...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    i am a catholic taught in parochial elementary...
49998    im going to have to disagree with the previous...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [46]:
text1="FYI this is not true"
text2="LAMO the class was so funny"
text3="I want it ASAP"

In [47]:
chat_words = {
    "AFAIK": "As Far As I Know",
    "AFK": "Away From Keyboard",
    "ASAP": "As Soon As Possible",
    "BTW": "By The Way",
    "B4": "Before",
    "LAMO": "Laughing My A** Off",
    "FYI": "For Your Information"
}

In [48]:
chat_words["ASAP"]

'As Soon As Possible'

In [49]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [51]:
text1

'FYI this is not true'

In [50]:
chat_conversion(text1)

'For Your Information this is not true'

In [52]:
text2

'LAMO the class was so funny'

In [53]:
chat_conversion(text2)

'Laughing My A** Off the class was so funny'

In [54]:
text3

'I want it ASAP'

In [55]:
chat_conversion(text3)

'I want it As Soon As Possible'

In [59]:
print((" ".join(["sunny","savit","data scientist","ML engineer"])))

sunny savit data scientist ML engineer